<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchAllCategories(){
        $qb = $this->createQueryBuilder('a');
        return $qb->select('a')
            ->orderBy('a.ordering', 'ASC')
            ->getQuery();
    }

}
