<?php

namespace AppBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchOrdersByUser($userId){

        $qb = $this->createQueryBuilder('a');

        return $qb->select('a')
            ->where($qb->expr()->eq('a.user', ':userId') )
            ->setParameter(':userId', $userId)
            ->orderBy('a.id', 'DESC')
            ->getQuery();
    }


}
