<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Symfony\Component\HttpFoundation\Request;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchProductsByUser($userId){

        $qb = $this->createQueryBuilder('a');

        return $qb->select('a')
            ->where($qb->expr()->eq('a.user', ':userId') )
            ->setParameter(':userId', $userId)
            ->orderBy('a.id', 'DESC')
            ->getQuery();
    }

    public function fetchAllProducts(){
        $qb = $this->createQueryBuilder('a')
            ->join('a.category', 'c')
            ->join('a.user', 'u');
        return $qb->select('a')
            ->orderBy('a.id', 'DESC')
            ->getQuery();
    }


    public function fetchProductsByCat(Category $category){

        $qb = $this->createQueryBuilder('p');

        return $qb->select('p')
            ->where($qb->expr()->eq('p.category', ':catId') )
            ->andWhere($qb->expr()->orX(
                $qb->expr()->gt('p.qty', 0),
                $qb->expr()->isNull('p.qty')
            ))
            ->setParameter(':catId', $category)
            ->orderBy('p.id', 'DESC')
            ->getQuery();
    }

}
