<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Symfony\Component\HttpFoundation\Request;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchProductsByUser($userId){

        $qb = $this->createQueryBuilder('p');

        return $qb->select('p')
            ->where($qb->expr()->eq('p.user', ':userId') )
            ->setParameter(':userId', $userId)
            ->orderBy('p.id', 'DESC')
            ->getQuery();
    }


    public function fetchProductsByCat(Category $category){

        $qb = $this->createQueryBuilder('p');

        return $qb->select('p')
            ->where($qb->expr()->eq('p.category', ':catId') )
            ->setParameter(':catId', $category)
            ->orderBy('p.id', 'DESC')
            ->getQuery();
    }

}
