<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function fetchAllUsers(){
        $qb = $this->createQueryBuilder('a');
        return $qb->select('a')
            ->orderBy('a.id', 'DESC')
            ->getQuery();
    }

}
