# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.price_calculator:
        class: AppBundle\Service\PriceCalculator
        arguments: ['@doctrine.orm.entity_manager']
    app.get_categories:
            class: AppBundle\Service\GetCategories
            arguments: ['@doctrine.orm.entity_manager']
    app.get_roles:
                class: AppBundle\Service\GetRoles
                arguments: ['@doctrine.orm.entity_manager']
    app.cart:
                class: AppBundle\Service\Cart
                arguments: ['@doctrine.orm.entity_manager', '@session', '@app.price_calculator']